### ISSUE TITLE
Fix "your-github-name" in README

### ISSUE THREAD

**Issue by freitagbr** [freitagbr/cr-multihash#1]
The README contains "your-github-name" references everywhere. These should be replaced with the maintainer's name.

**Comment by nfischer** [comment]
@freitagbr @IvantheDugtrio this was fixed in #2, right?

For future reference, if you write something like `Fixes #1` in the body of your PR, then merging the PR automatically closes the issue. Apparently this does not work if you put something like `Fix to issue #1` in the subject of the PR :confused:

**Comment by freitagbr** [comment]
Correct, this was fixed in #2. GitHub needs better NLP for PR descriptions...
